export enum Colors {
  MainWhite = '#ffffff',
  MainGreyPrimary = '#4F4F4F',
  MainGreySecondary = '#828282',
  MainGreyTertiary = '#BDBDBD',
  MainGreyLight = '#F2F2F2',
  MainBlack = '#333333',
  MainBlue = '#F1F8FC',
  MainBluePrimary = '#5876C5',
  MainGreenPrimary = '#2B9999',
  MainGreenSecondary = '#1FC5C7',
  AdditionalGreen = '#28C783',
  AdditionalBlue = '#00beff',
  AdditionalBlueDark = '#0183b0',
  AdditionalOrange = '#FFE0BD',
  AdditionalPinkSecondary = '#E14665',
  AdditionalPinkPrimary = '#FFD2DB',
}
