export const routerPath = {
  home: '/',
  analiticCard: 'analitic-card',
  reports: 'reports',
  settings: 'settings',
  primeCost: 'prime-cost',
  login: '/login',
  registration: 'registration',
  passwordRecovery: 'recovery-pass',
  passwordReset: 'reset-pass',
  balance: 'balance',
  weeks: '/admin-panel/weeks',
  users: '/admin-panel/users',
  searchTerms: '/admin-panel/search-terms',
  analiticsOwn: '/analitics-own',
  analiticsOther: '/analitics-other',
  searchQuery: '/search-query',
  notFound: '*',
};
