export const data = [
  {
    article: '1111',
    date: '2023-02-28',
    parameters: [
      {
        title: 'трусы новые',
        statistics: [
          {
            msk: 0,
            spb: 0,
            ekb: 2,
            kzn: 0,
            nsk: 0,
            hbr: 0,
            kdr: 0,
            klgd: 0,
          },
          {
            msk: 0,
            spb: 0,
            ekb: 1,
            kzn: 0,
            nsk: 0,
            hbr: 0,
            kdr: 0,
            klgd: 0,
          },
          {
            msk: 0,
            spb: 0,
            ekb: 2,
            kzn: 0,
            nsk: 0,
            hbr: 0,
            kdr: 0,
            klgd: 0,
          },
          {
            msk: 0,
            spb: 0,
            ekb: 1,
            kzn: 0,
            nsk: 0,
            hbr: 0,
            kdr: 0,
            klgd: 0,
          },
          {
            msk: 0,
            spb: 0,
            ekb: 2,
            kzn: 0,
            nsk: 0,
            hbr: 0,
            kdr: 0,
            klgd: 0,
          },
          {
            msk: 0,
            spb: 0,
            ekb: 2,
            kzn: 0,
            nsk: 0,
            hbr: 0,
            kdr: 0,
            klgd: 0,
          },
          {
            msk: 0,
            spb: 0,
            ekb: 2,
            kzn: 0,
            nsk: 0,
            hbr: 0,
            kdr: 0,
            klgd: 0,
          },
        ],
      },
      {
        title: 'трусы старые',
        statistics: [
          {
            msk: 0,
            spb: 0,
            ekb: 2,
            kzn: 0,
            nsk: 0,
            hbr: 0,
            kdr: 0,
            klgd: 0,
          },
          {
            msk: 0,
            spb: 0,
            ekb: 1,
            kzn: 0,
            nsk: 0,
            hbr: 0,
            kdr: 0,
            klgd: 0,
          },
          {
            msk: 0,
            spb: 0,
            ekb: 2,
            kzn: 0,
            nsk: 0,
            hbr: 0,
            kdr: 0,
            klgd: 0,
          },
          {
            msk: 0,
            spb: 0,
            ekb: 1,
            kzn: 0,
            nsk: 0,
            hbr: 0,
            kdr: 0,
            klgd: 0,
          },
          {
            msk: 0,
            spb: 0,
            ekb: 2,
            kzn: 0,
            nsk: 0,
            hbr: 0,
            kdr: 0,
            klgd: 0,
          },
          {
            msk: 0,
            spb: 0,
            ekb: 2,
            kzn: 0,
            nsk: 0,
            hbr: 0,
            kdr: 0,
            klgd: 0,
          },
          {
            msk: 0,
            spb: 0,
            ekb: 2,
            kzn: 0,
            nsk: 0,
            hbr: 0,
            kdr: 0,
            klgd: 0,
          },
        ],
      },
      {
        title: 'трусы новые',
        statistics: [
          {
            msk: 0,
            spb: 0,
            ekb: 2,
            kzn: 0,
            nsk: 0,
            hbr: 0,
            kdr: 0,
            klgd: 0,
          },
          {
            msk: 0,
            spb: 0,
            ekb: 1,
            kzn: 0,
            nsk: 0,
            hbr: 0,
            kdr: 0,
            klgd: 0,
          },
          {
            msk: 0,
            spb: 0,
            ekb: 2,
            kzn: 0,
            nsk: 0,
            hbr: 0,
            kdr: 0,
            klgd: 0,
          },
          {
            msk: 0,
            spb: 0,
            ekb: 1,
            kzn: 0,
            nsk: 0,
            hbr: 0,
            kdr: 0,
            klgd: 0,
          },
          {
            msk: 0,
            spb: 0,
            ekb: 2,
            kzn: 0,
            nsk: 0,
            hbr: 0,
            kdr: 0,
            klgd: 0,
          },
          {
            msk: 0,
            spb: 0,
            ekb: 2,
            kzn: 0,
            nsk: 0,
            hbr: 0,
            kdr: 0,
            klgd: 0,
          },
          {
            msk: 0,
            spb: 0,
            ekb: 2,
            kzn: 0,
            nsk: 0,
            hbr: 0,
            kdr: 0,
            klgd: 0,
          },
        ],
      },
      {
        title: 'трусы старые',
        statistics: [
          {
            msk: 0,
            spb: 0,
            ekb: 2,
            kzn: 0,
            nsk: 0,
            hbr: 0,
            kdr: 0,
            klgd: 0,
          },
          {
            msk: 0,
            spb: 0,
            ekb: 1,
            kzn: 0,
            nsk: 0,
            hbr: 0,
            kdr: 0,
            klgd: 0,
          },
          {
            msk: 0,
            spb: 0,
            ekb: 2,
            kzn: 0,
            nsk: 0,
            hbr: 0,
            kdr: 0,
            klgd: 0,
          },
          {
            msk: 0,
            spb: 0,
            ekb: 1,
            kzn: 0,
            nsk: 0,
            hbr: 0,
            kdr: 0,
            klgd: 0,
          },
          {
            msk: 0,
            spb: 0,
            ekb: 2,
            kzn: 0,
            nsk: 0,
            hbr: 0,
            kdr: 0,
            klgd: 0,
          },
          {
            msk: 0,
            spb: 0,
            ekb: 2,
            kzn: 0,
            nsk: 0,
            hbr: 0,
            kdr: 0,
            klgd: 0,
          },
          {
            msk: 0,
            spb: 0,
            ekb: 2,
            kzn: 0,
            nsk: 0,
            hbr: 0,
            kdr: 0,
            klgd: 0,
          },
        ],
      },
    ],
  },
  {
    article: '2222',
    date: '2023-02-28',
    parameters: [
      {
        title: 'кеды новые',
        statistics: [
          {
            msk: 0,
            spb: 0,
            ekb: 2,
            kzn: 0,
            nsk: 0,
            hbr: 0,
            kdr: 0,
            klgd: 0,
          },
          {
            msk: 0,
            spb: 0,
            ekb: 1,
            kzn: 0,
            nsk: 0,
            hbr: 0,
            kdr: 0,
            klgd: 0,
          },
          {
            msk: 0,
            spb: 0,
            ekb: 2,
            kzn: 0,
            nsk: 0,
            hbr: 0,
            kdr: 0,
            klgd: 0,
          },
          {
            msk: 0,
            spb: 0,
            ekb: 1,
            kzn: 0,
            nsk: 0,
            hbr: 0,
            kdr: 0,
            klgd: 0,
          },
          {
            msk: 0,
            spb: 0,
            ekb: 2,
            kzn: 0,
            nsk: 0,
            hbr: 0,
            kdr: 0,
            klgd: 0,
          },
          {
            msk: 0,
            spb: 0,
            ekb: 2,
            kzn: 0,
            nsk: 0,
            hbr: 0,
            kdr: 0,
            klgd: 0,
          },
          {
            msk: 0,
            spb: 0,
            ekb: 2,
            kzn: 0,
            nsk: 0,
            hbr: 0,
            kdr: 0,
            klgd: 0,
          },
        ],
      },
      {
        title: 'кеды старые',
        statistics: [
          {
            msk: 0,
            spb: 0,
            ekb: 2,
            kzn: 0,
            nsk: 0,
            hbr: 0,
            kdr: 0,
            klgd: 0,
          },
          {
            msk: 0,
            spb: 0,
            ekb: 1,
            kzn: 0,
            nsk: 0,
            hbr: 0,
            kdr: 0,
            klgd: 0,
          },
          {
            msk: 0,
            spb: 0,
            ekb: 2,
            kzn: 0,
            nsk: 0,
            hbr: 0,
            kdr: 0,
            klgd: 0,
          },
          {
            msk: 0,
            spb: 0,
            ekb: 1,
            kzn: 0,
            nsk: 0,
            hbr: 0,
            kdr: 0,
            klgd: 0,
          },
          {
            msk: 0,
            spb: 0,
            ekb: 2,
            kzn: 0,
            nsk: 0,
            hbr: 0,
            kdr: 0,
            klgd: 0,
          },
          {
            msk: 0,
            spb: 0,
            ekb: 2,
            kzn: 0,
            nsk: 0,
            hbr: 0,
            kdr: 0,
            klgd: 0,
          },
          {
            msk: 0,
            spb: 0,
            ekb: 2,
            kzn: 0,
            nsk: 0,
            hbr: 0,
            kdr: 0,
            klgd: 0,
          },
        ],
      },
    ],
  },
];
